version: '3'

services:
  app:
    user: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "5000:5000"
    command: sleep infinity
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 'pokemon'
      POSTGRES_USER: 'ash'
      POSTGRES_DB: 'pokeapi'
    volumes:
      - ../Migrations:/docker-entrypoint-initdb.d
